-- Activation du bon encodage
SET client_encoding = 'WIN-1252';

-- Insertion dans la table user_
INSERT INTO public.user_ (id, email, name, firstname, validation_date, password, id_admin) VALUES
('b49f1f09-6798-421d-9546-f1792d952f39', 'fanasinamanantsoa30@gmail.com', '', 'Admin', '2025-03-12 00:00:00', '$2a$06$pCXEF8jtguYwXZEk3qy8vuWqt8ZgsTIfGp2ZajYvSp2qakZ1Kt9Qq', true);

-- Insertion dans la table configuration
INSERT INTO public.configuration (id, keys, valeurs) VALUES
(DEFAULT, 'pin_expiration_minute', '10'),
(DEFAULT, 'pin_length', '6'),
(DEFAULT, 'sending_email_pin_content', 'Nous vous envoyons un pin de connexion.'),
(DEFAULT, 'count_attempt', '3'),
(DEFAULT, 'next_attempt_minute', '10');

-- Insertion dans la table general_info
INSERT INTO public.general_info (id, cle, icone, lien, id_general_info) VALUES
(DEFAULT, 'a_propos', NULL, NULL, NULL),
(DEFAULT, 'dgi', NULL, NULL, NULL),
(DEFAULT, 'mot_du_dgi', NULL, NULL, NULL),
(DEFAULT, '/legislation', NULL, NULL, NULL),
(DEFAULT, '/ressources', NULL, NULL, NULL),
(DEFAULT, '/analytiques_fiscales', NULL, NULL, NULL),
(DEFAULT, '/historique', NULL, NULL, NULL),
(DEFAULT, '/vision', NULL, NULL, NULL),
(DEFAULT, '/attributions', NULL, NULL, NULL),
(DEFAULT, '/e_service', NULL, NULL, NULL),
(DEFAULT, '/votre_avis', NULL, NULL, NULL),
(DEFAULT, 'centre_contact', NULL, NULL, NULL),
(DEFAULT, 'navigation', NULL, NULL, NULL),
(DEFAULT, 'nav_accueil', NULL, '#top', 13),
(DEFAULT, 'nav_a_propos', NULL, '#apropos', 13),
(DEFAULT, 'nav_documentations', NULL, '#documentations', 13),
(DEFAULT, 'nav_e_service', NULL, '#safi', 13),
(DEFAULT, 'nav_actualites', NULL, '#actualites', 13),
(DEFAULT, 'nav_espace', NULL, '#torohy', 13),
(DEFAULT, 'nav_contact', NULL, '#contact', 13),
(DEFAULT, 'actualites', NULL, NULL, NULL),
(DEFAULT, 'partenaire', NULL, NULL, NULL),
(DEFAULT, 'bureau', NULL, NULL, NULL),
(DEFAULT, 'contribuable', NULL, NULL, NULL),
(DEFAULT, 'recette', NULL, NULL, NULL),
(DEFAULT, 'appeler', NULL, '#appeler', NULL),
(DEFAULT, 'ecrire', NULL, '#ecrire', NULL),
(DEFAULT, 'visiter', NULL, '#visiter', NULL),
(DEFAULT, '/vision/valeurs et engagements', NULL, '/admin/explorer?path=/vision/valeurs et engagements', 8),
(DEFAULT, '/vision/projets de modernisation', NULL, '/admin/explorer?path=/vision/projets de modernisation', 8),
(DEFAULT, '/legislation/Recueil des textes', NULL, 'https://portal.impots.mg/textes/', 4),
(DEFAULT, '/legislation/Rescrit fiscal', NULL, 'https://portal.impots.mg/rescrit/', 4),
(DEFAULT, '/legislation/Brochures et guides', NULL, '/admin/explorer?path=/legislation/Brochures et guides', 4),
(DEFAULT, '/legislation/Calendrier Fiscal', NULL, '/admin/explorer?path=/legislation/Calendrier Fiscal', 4),
(DEFAULT, '/legislation/Conventions et Régimes Spéciaux', NULL, '/admin/explorer?path=/legislation/Conventions et Régimes Spéciaux', 4),
(DEFAULT, '/legislation/Codes et Manuels', NULL, '/admin/explorer?path=/legislation/Codes et Manuels', 4),
(DEFAULT, '/ressources/SIRH', NULL, 'https://sysinfo.mef.gov.mg:9101/ROHI/index.php/accueil/login', 5),
(DEFAULT, '/ressources/G-formation', NULL, 'https://portal.impots.mg/portal/utilisateur', 5),
(DEFAULT, '/ressources/Annuaire', NULL, '/admin/explorer?path=/ressources/Annuaire', 5),
(DEFAULT, '/ressources/Recrutements', NULL, '/admin/explorer?path=/ressources/Recrutements', 5),
(DEFAULT, '/ressources/Budget de la DGI', NULL, '/admin/explorer?path=/ressources/Budget de la DGI', 5),
(DEFAULT, '/ressources/RCTVA', NULL, '/admin/explorer?path=/ressources/RCTVA', 5),
(DEFAULT, '/e_service/Ehetra', NULL, 'https://e-hetra.impots.mg/', 10),
(DEFAULT, '/e_service/HetraOnline', NULL, 'https://hetraonline.impots.mg/', 10),
(DEFAULT, '/e_service/Valeur administrative des immeubles', NULL, 'https://immo.impots.mg/', 10),
(DEFAULT, '/e_service/Valeur administrative des véhicules', NULL, 'https://vehicule.impots.mg/', 10),
(DEFAULT, '/e_service/Attestation de destination', NULL, 'http://www.a2d.impots.mg/', 10),
(DEFAULT, '/e_service/Simulateur de calcul d''impôt', NULL, 'https://www.impots.mg/fr/simulator', 10),
(DEFAULT, '/e_service/DConline', NULL, 'https://entreprises.impots.mg/dconline/', 10),
(DEFAULT, '/e_service/Annexe TVA', NULL, 'https://entreprises.impots.mg/nifonline/annexe_tva.php?bash=02122#accueil_menu_annexe_tva', 10);

-- Insertion dans la table langue
INSERT INTO public.langue (id, nom, icon) VALUES
(1, 'MLG', NULL),
(2, 'FRA', NULL),
(3, 'ENG', NULL);

-- Insertion dans la table general_info_valeur
INSERT INTO public.general_info_valeur (id, titre, valeur, entete, bouton, id_langue, id_general_info) VALUES
(DEFAULT, 'Fandraisana', 'Fandraisana', '', '', 1, 14),
(DEFAULT, 'Momba ny', 'Momba ny', '', '', 1, 15),
(DEFAULT, 'Tahirin-kevitra', 'Tahirin-kevitra', '', '', 1, 16),
(DEFAULT, 'E-Service', 'E-Service', '', '', 1, 17),
(DEFAULT, 'Vaovao', 'Vaovao', '', '', 1, 18),
(DEFAULT, 'Espace citoyen', 'Espace citoyen', '', '', 1, 19),
(DEFAULT, 'Ivontoerana fifandraisana', 'Ivontoerana fifandraisana', '', '', 1, 20),
(DEFAULT, 'Vaovao', '', '', '', 1, 21),
(DEFAULT, 'Mpiara-miasa', '', '', '', 1, 22),
(DEFAULT, '<p>Bureaux op&eacute;rationnels</p>', '<p><br></p>', '153', '', 1, 23),
(DEFAULT, '<p>Contribuables enregistr&eacute;s</p>', '<p><br></p>', '1585274', '', 1, 24),
(DEFAULT, '<p>Recettes collect&eacute;es</p>', '<p><br></p>', '4754124452922', '', 1, 25),
(DEFAULT, 'Accueil', 'Accueil', '', '', 2, 14),
(DEFAULT, '&Agrave; propos', '&Agrave; propos', '', '', 2, 15),
(DEFAULT, 'Documentations', 'Documentations', '', '', 2, 16),
(DEFAULT, 'E-Services', 'E-Services', '', '', 2, 17),
(DEFAULT, 'Actualit&eacute;s', 'Actualit&eacute;s', '', '', 2, 18),
(DEFAULT, 'Espace citoyen', 'Espace citoyen', '', '', 2, 19),
(DEFAULT, 'Centre de contact', 'Centre de contact', '', '', 2, 20),
(DEFAULT, 'actualit&eacute;s', '', '', '', 2, 21),
(DEFAULT, 'partenaires', '', '', '', 2, 22),
(DEFAULT, '<p>Bureaux op&eacute;rationnels</p>', '<p><br></p>', '153', '', 2, 23),
(DEFAULT, '<p>Contribuables enregistr&eacute;s</p>', '<p><br></p>', '1585274', '', 2, 24),
(DEFAULT, '<p>Recettes collect&eacute;es</p>', '<p><br></p>', '4754124452922', '', 2, 25),
(DEFAULT, 'Home', 'Home', '', '', 3, 14),
(DEFAULT, 'About', 'About', '', '', 3, 15),
(DEFAULT, 'Documentations', 'Documentations', '', '', 3, 16),
(DEFAULT, 'E-Services', 'E-Services', '', '', 3, 17),
(DEFAULT, 'News', 'News', '', '', 3, 18),
(DEFAULT, 'Citizen Space', 'Citizen Space', '', '', 3, 19),
(DEFAULT, 'Contact Center', 'Contact Center', '', '', 3, 20),
(DEFAULT, 'news', '', '', '', 3, 21),
(DEFAULT, 'partners', '', '', '', 3, 22),
(DEFAULT, '<p>Bureaux op&eacute;rationnels</p>', '<p><br></p>', '153', '', 3, 23),
(DEFAULT, '<p>Contribuables enregistr&eacute;s</p>', '<p><br></p>', '1585274', '', 3, 24),
(DEFAULT, '<p>Recettes collect&eacute;es</p>', '<p><br></p>', '4754124452922', '', 3, 25),
(DEFAULT, 'Mikasika', 'Mikasika', '', '', 1, 1),
(DEFAULT, '&Agrave; propos', '&Agrave; propos', '', '', 2, 1),
(DEFAULT, 'About', 'About', '', '', 3, 1),
(DEFAULT, 'Tantara', 'Tantara ny DGI', 'Tantara', '', 1, 7),
(DEFAULT, 'Historique', 'Historique de la DGI', 'Historique', '', 2, 7),
(DEFAULT, 'History', 'History of the DGI', 'History', '', 3, 7),
(DEFAULT, '<p>Fahitana</p>', '<p>T&eacute;l&eacute;chargez ici l''ensemble des documents fondateurs </p><p>qui d&eacute;finissent notre engagement d''excellence </p><p>au service des contribuables et du d&eacute;veloppement &eacute;conomique.</p>', 'Fahitana', '', 1, 8),
(DEFAULT, '<p>Vision de la DGI</p>', '<p>T&eacute;l&eacute;chargez ici l''ensemble des documents fondateurs </p><p>qui d&eacute;finissent notre engagement d''excellence </p><p>au service des contribuables et du d&eacute;veloppement &eacute;conomique.</p>', 'Vision', '', 2, 8),
(DEFAULT, '<p>Vision of DGI</p>', '<p>Download here all the founding documents </p><p>that define our commitment to excellence </p><p>in serving taxpayers and economic development.</p>', 'Vision', '', 3, 8),
(DEFAULT, '<p>Adidy</p>', '<p>Adidy sy andraikitra</p>', '', '', 1, 9),
(DEFAULT, '<p>Attributions de la DGI</p>', '<p>Explorez ici l''organisation </p><p>d&eacute;taill&eacute;e de la DGI </p><p>de Madagascar.</p><p><br></p>', 'Attributions', '', 2, 9),
(DEFAULT, '<p>Responsibilities of DGI</p>', '<p>Duties and responsibilities</p>', 'Responsibilities', '', 3, 9),
(DEFAULT, '<p>Votre Avis</p>', '<p>Exprimez votre avis sur nos services et contribuez &agrave; la lutte contre la fraude fiscale &agrave; travers notre plateforme s&eacute;curis&eacute;e de signalement.</p>', 'espace citoyen', 'Donner mon avis', 2, 11),
(DEFAULT, '<p>Centre de Contact</p>', '<p>Bient&ocirc;t, notre centre d''appel sera disponible pour toute information sur vos d&eacute;marches fiscales. Nos conseillers seront &agrave; votre &eacute;coute, 24h/24 et 7j/7.</p>', 'Nous sommes l&agrave; pour vous', 'Nous contacter', 2, 12),
(DEFAULT, '<p>Contact Center</p>', '<p>Soon, our call center will be available for any information regarding your tax procedures. Our advisors will be at your service, 24/7.</p>', 'We are here for you', 'Contact us', 3, 12),
(DEFAULT, '<p>Ivontoerana Fifandraisana</p>', '<p>Bient&ocirc;t, notre centre d''appel sera disponible pour toute information sur vos d&eacute;marches fiscales. Nos conseillers seront &agrave; votre &eacute;coute, 24h/24 et 7j/7.</p>', 'Miaraka aminay ianao', 'Mifandraisa aminay', 1, 12),
(DEFAULT, '<p>Loharano</p>', '<p>Acc&eacute;dez &agrave; toutes les informations sur l''organisation de la Direction G&eacute;n&eacute;rale des Imp&ocirc;ts : son &eacute;quipe dirigeante, ses responsables et ses structures op&eacute;rationnelles.</p>', '', 'hijery', 1, 5),
(DEFAULT, '<p>Ressources</p>', '<p>Acc&eacute;dez &agrave; toutes les informations sur l''organisation de la Direction G&eacute;n&eacute;rale des Imp&ocirc;ts : son &eacute;quipe dirigeante, ses responsables et ses structures op&eacute;rationnelles.</p>', '', 'voir plus', 2, 5),
(DEFAULT, '<p>Tenin''i DGI</p>', '<p>Engag&eacute;e dans une transformation digitale majeure &agrave; travers son nouveau Syst&egrave;me d''Administration Fiscale Int&eacute;gr&eacute; (SAFI), la DGI vous accueille sur son portail en ligne, incarnant sa vision d''une administration fiscale innovante, transparente et pilier de l''&eacute;mergence. D&eacute;couvrez nos services modernes, con&ccedil;us pour garantir votre satisfaction et pr&eacute;server un climat de confiance, conform&eacute;ment &agrave; l''image d''un gouvernement "manakaiky vahoaka".</p>', 'DGI', '', 1, 3),
(DEFAULT, '<p>Your Opinion</p>', '<p>Express your opinion on our services and contribute to the fight against tax fraud through our secure reporting platform.</p>', 'espace citoyen', 'Give feedback', 3, 11),
(DEFAULT, '<p>Hevitrao</p>', '<p>Exprimez votre avis sur nos services et contribuez &agrave; la lutte contre la fraude fiscale &agrave; travers notre plateforme s&eacute;curis&eacute;e de signalement.</p>', 'espace citoyen', 'Omeo hevitra', 1, 11),
(DEFAULT, '<p>Mot du DGI</p>', '<p>Engag&eacute;e dans une transformation digitale majeure &agrave; travers son nouveau Syst&egrave;me d''Administration Fiscale Int&eacute;gr&eacute; (SAFI), la DGI vous accueille sur son portail en ligne, incarnant sa vision d''une administration fiscale innovante, transparente et pilier de l''&eacute;mergence. D&eacute;couvrez nos services modernes, con&ccedil;us pour garantir votre satisfaction et pr&eacute;server un climat de confiance, conform&eacute;ment &agrave; l''image d''un gouvernement "manakaiky vahoaka".</p>', 'DGI', '', 2, 3),
(DEFAULT, '<p>E-Service</p>', '<p>Simplifiez vos obligations fiscales avec SAFI, la plateforme digitale de la Direction G&eacute;n&eacute;rale des Imp&ocirc;ts qui vous permet de d&eacute;clarer, payer et suivre vos imp&ocirc;ts en ligne, avec un syst&egrave;me d''alertes personnalis&eacute;es pour une gestion optimale de votre compte.</p>', 'D&eacute;marches fiscales', 'Se connecter', 2, 10),
(DEFAULT, '<p>L&eacute;gislation</p>', '<p>Retrouvez ici l''ensemble des textes et r&eacute;glementations en vigueur r&eacute;gissant la fiscalit&eacute; malgache, r&eacute;guli&egrave;rement actualis&eacute;s pour vous permettre de mieux comprendre vos droits et obligations fiscales.</p>', '', 'voir plus', 2, 4),
(DEFAULT, '<p>Legislation</p>', '<p>Find here all the current texts and regulations governing Malagasy taxation, regularly updated to help you better understand your tax rights and obligations.</p>', '', 'show more', 3, 4),
(DEFAULT, '<p>Lalana</p>', '<p>Retrouvez ici l''ensemble des textes et r&eacute;glementations en vigueur r&eacute;gissant la fiscalit&eacute; malgache, r&eacute;guli&egrave;rement actualis&eacute;s pour vous permettre de mieux comprendre vos droits et obligations fiscales.</p>', '', 'hijery', 1, 4),
(DEFAULT, '<p>Resources</p>', '<p>Access all the information about the organization of the Directorate General of Taxes: its management team, its officials, and its operational structures.</p>', '', 'show more', 3, 5),
(DEFAULT, '<p>Famakafakana ara-bola</p>', '<p>Consultez dans cette rubrique les documents d''analyse approfondis retra&ccedil;ant ses performances en mati&egrave;re de mobilisation des recettes fiscales, statistiques p&eacute;riodiques des r&eacute;alisations, &eacute;tudes sectorielles, publications &eacute;conomiques, rapports d&eacute;taill&eacute;s d''activit&eacute;s, etc.</p>', '', 'hijery', 1, 6),
(DEFAULT, '<p>E-Service</p>', '<p>Simplify your tax obligations with SAFI, the digital platform of the Directorate General of Taxes that allows you to declare, pay, and track your taxes online, with a personalized alert system for optimal account management.</p>', 'Tax procedures', 'Log in', 3, 10),
(DEFAULT, '<p>E-Service</p>', '<p>Simplifiez vos obligations fiscales avec SAFI, la plateforme digitale de la Direction G&eacute;n&eacute;rale des Imp&ocirc;ts qui vous permet de d&eacute;clarer, payer et suivre vos imp&ocirc;ts en ligne, avec un syst&egrave;me d''alertes personnalis&eacute;es pour une gestion optimale de votre compte.</p>', 'D&eacute;marches fiscales', 'Se connecter', 1, 10),
(DEFAULT, '<p>Tale jeneralin''ny hetra</p>', '<p>Germain</p>', 'Ny mombamomba', '', 1, 2),
(DEFAULT, '<p>Directeur G&eacute;n&eacute;ral des Imp&ocirc;ts</p>', '<p>Germain</p>', '&agrave; propos', '', 2, 2),
(DEFAULT, '<p>Director General of Taxes</p>', '<p>Germain</p>', 'about', '', 3, 2),
(DEFAULT, '<p>Analytiques fiscales</p>', '<p>Consultez dans cette rubrique les documents d''analyse approfondis retra&ccedil;ant ses performances en mati&egrave;re de mobilisation des recettes fiscales, statistiques p&eacute;riodiques des r&eacute;alisations, &eacute;tudes sectorielles, publications &eacute;conomiques, rapports d&eacute;taill&eacute;s d''activit&eacute;s, etc.</p>', '', 'voir plus', 2, 6),
(DEFAULT, '<p>Fiscal analytics</p>', '<p>Consult in this section detailed analysis documents tracing its performance in mobilizing tax revenues, periodic statistics of achievements, sectoral studies, economic publications, detailed activity reports, etc.</p>', '', 'show more', 3, 6),
(DEFAULT, '<p>Word of the DGI</p>', '<p>Committed to a major digital transformation through its new Integrated Tax Administration System (SAFI), the DGI welcomes you to its online portal, embodying its vision of an innovative, transparent tax administration and a pillar of emergence. Discover our modern services, designed to ensure your satisfaction and maintain a climate of trust, in line with the image of a government "close to the people".</p>', 'DGI', '', 3, 3),
(DEFAULT, 'Appeler', 'Secr&eacute;tariat DGI : +261 20 85 287 08<br>Cellule Communication DGI : +261 32 12 015 03<br>Cellule eHetra : +261 32 12 015 04<br>Hotline SSIF : +261 32 12 011 74 / +261 34 49 431 52', 'NOUS CONTACTER', '', 2, 26),
(DEFAULT, 'Ecrire', 'Secr&eacute;tariat DGI : dgimpots@moov.mg<br>Cellule Communication DGI : communication.dgimpots@gmail.com<br>Hotline SSIF : impot.ssif.hotline@gmail.com', '', '', 2, 27),
(DEFAULT, 'Visiter', 'Immeuble de l''&Eacute;conomie et des Finances<br>4&egrave;me &eacute;tage - porte 420<br>Antaninarenina Antananarivo', '', '', 2, 28),
(DEFAULT, 'Call', 'DGI Secretariat: +261 20 85 287 08<br>DGI Communication Unit: +261 32 12 015 03<br>eHetra Unit: +261 32 12 015 04<br>SSIF Hotline: +261 32 12 011 74 / +261 34 49 431 52', 'CONTACT US', '', 3, 26),
(DEFAULT, 'Write', 'DGI Secretariat: dgimpots@moov.mg<br>DGI Communication Unit: communication.dgimpots@gmail.com<br>SSIF Hotline: impot.ssif.hotline@gmail.com', '', '', 3, 27),
(DEFAULT, 'Visit', 'Ministry of Economy and Finance Building<br>4th floor - door 420<br>Antaninarenina Antananarivo', '', '', 3, 28),
(DEFAULT, 'Antsoy', 'Sekreterian''ny DGI : +261 20 85 287 08<br>Sampan''asa Fampandraharahana DGI : +261 32 12 015 03<br>Sampan''asa eHetra : +261 32 12 015 04<br>Hotline SSIF : +261 32 12 011 74 / +261 34 49 431 52', 'Hifandray aminay', '', 1, 26),
(DEFAULT, 'Hanoratra', 'Sekreterian''ny DGI : dgimpots@moov.mg<br>Sampan''asa Fampandraharahana DGI : communication.dgimpots@gmail.com<br>Hotline SSIF : impot.ssif.hotline@gmail.com', '', '', 1, 27),
(DEFAULT, 'Hitsidika', 'Tranon''ny Toekarena sy ny Finansa<br>4&egrave;me &eacute;tage - varavarana 420<br>Antaninarenina Antananarivo', '', '', 1, 28),
(DEFAULT, '', '', '', '', 1, 29),
(DEFAULT, '', '', '', '', 2, 29),
(DEFAULT, '', '', '', '', 3, 29),
(DEFAULT, '', '', '', '', 1, 30),
(DEFAULT, '', '', '', '', 2, 30),
(DEFAULT, '', '', '', '', 3, 30),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 31),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 31),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 31),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 32),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 32),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 32),
(DEFAULT, '<p><br></p>', '<p>Retrouvez tous nos guides et brochures d''information pour vous accompagner dans la compr&eacute;hension et l''accomplissement de vos obligations fiscales.</p>', '', '', 1, 33),
(DEFAULT, '<p><br></p>', '<p>Retrouvez tous nos guides et brochures d''information pour vous accompagner dans la compr&eacute;hension et l''accomplissement de vos obligations fiscales.</p>', '', '', 2, 33),
(DEFAULT, '<p><br></p>', '<p>Find all our guides and information brochures to assist you in understanding and fulfilling your tax obligations.</p>', '', '', 3, 33),
(DEFAULT, '', '', '', '', 1, 34),
(DEFAULT, '', '', '', '', 2, 34),
(DEFAULT, '', '', '', '', 3, 34),
(DEFAULT, '', '', '', '', 1, 35),
(DEFAULT, '', '', '', '', 2, 35),
(DEFAULT, '', '', '', '', 3, 35),
(DEFAULT, '<p><br></p>', '<p>Consultez ici l''ensemble des codes fiscaux et manuels de r&eacute;f&eacute;rence.</p>', '', '', 1, 36),
(DEFAULT, '<p><br></p>', '<p>Consultez ici l''ensemble des codes fiscaux et manuels de r&eacute;f&eacute;rence.</p>', '', '', 2, 36),
(DEFAULT, '<p><br></p>', '<p>Consult all tax codes and reference manuals here.</p>', '', '', 3, 36),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 37),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 37),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 37),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 38),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 38),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 38),
(DEFAULT, '<p><br></p>', '<p>Acc&eacute;dez aux coordonn&eacute;es compl&egrave;tes de nos services centraux et r&eacute;gionaux pour faciliter vos contacts et d&eacute;marches aupr&egrave;s de la DGI.</p>', '', '', 1, 39),
(DEFAULT, '<p><br></p>', '<p>Acc&eacute;dez aux coordonn&eacute;es compl&egrave;tes de nos services centraux et r&eacute;gionaux pour faciliter vos contacts et d&eacute;marches aupr&egrave;s de la DGI.</p>', '', '', 2, 39),
(DEFAULT, '<p><br></p>', '<p>Access the complete contact details of our central and regional services to facilitate your interactions and procedures with the DGI.</p>', '', '', 3, 39),
(DEFAULT, '', '', '', '', 1, 40),
(DEFAULT, '', '', '', '', 2, 40),
(DEFAULT, '', '', '', '', 3, 40),
(DEFAULT, '', '', '', '', 1, 41),
(DEFAULT, '', '', '', '', 2, 41),
(DEFAULT, '', '', '', '', 3, 41),
(DEFAULT, '', '', '', '', 1, 42),
(DEFAULT, '', '', '', '', 2, 42),
(DEFAULT, '', '', '', '', 3, 42),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 43),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 43),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 43),
(DEFAULT, '', '', '', '', 1, 44),
(DEFAULT, '', '', '', '', 2, 44),
(DEFAULT, '', '', '', '', 3, 44),
(DEFAULT, '', '', '', '', 1, 45),
(DEFAULT, '', '', '', '', 2, 45),
(DEFAULT, '', '', '', '', 3, 45),
(DEFAULT, '', '', '', '', 1, 46),
(DEFAULT, '', '', '', '', 2, 46),
(DEFAULT, '', '', '', '', 3, 46),
(DEFAULT, '', '', '', '', 1, 47),
(DEFAULT, '', '', '', '', 2, 47),
(DEFAULT, '', '', '', '', 3, 47),
(DEFAULT, '', '', '', '', 1, 48),
(DEFAULT, '', '', '', '', 2, 48),
(DEFAULT, '', '', '', '', 3, 48),
(DEFAULT, '', '', '', '', 1, 49),
(DEFAULT, '', '', '', '', 2, 49),
(DEFAULT, '', '', '', '', 3, 49),
(DEFAULT, '', '', '', '', 1, 50),
(DEFAULT, '', '', '', '', 2, 50),
(DEFAULT, '', '', '', '', 3, 50);

-- Insertion dans la table user_pin
INSERT INTO public.user_pin (id, pin, creation_date, expiration_date, id_user) VALUES
(DEFAULT, '922655', '2025-03-12 02:52:15.586787', '2025-03-12 03:02:15.586787', 'b49f1f09-6798-421d-9546-f1792d952f39'),
(DEFAULT, '471457', '2025-03-12 08:53:21.965224', '2025-03-12 09:03:21.965224', 'b49f1f09-6798-421d-9546-f1792d952f39'),
(DEFAULT, '376341', '2025-03-12 09:15:01.27241', '2025-03-12 09:25:01.27241', 'b49f1f09-6798-421d-9546-f1792d952f39');