-- Activation de l'encodage UTF-8
SET client_encoding = 'WIN-1252';

-- Insertion dans la table user_
INSERT INTO public.user_ (id, email, name, firstname, validation_date, password, id_admin) VALUES
('b49f1f09-6798-421d-9546-f1792d952f39', 'fanasinamanantsoa30@gmail.com', '', 'Admin', '2025-03-12 00:00:00', '$2a$06$pCXEF8jtguYwXZEk3qy8vuWqt8ZgsTIfGp2ZajYvSp2qakZ1Kt9Qq', true);

-- Insertion dans la table configuration
INSERT INTO public.configuration (id, keys, valeurs) VALUES
(DEFAULT, 'pin_expiration_minute', '10'),
(DEFAULT, 'pin_length', '6'),
(DEFAULT, 'sending_email_pin_content', 'Nous vous envoyons un pin de connexion.'),
(DEFAULT, 'count_attempt', '3'),
(DEFAULT, 'next_attempt_minute', '10');

-- Insertion dans la table general_info
INSERT INTO public.general_info (id, cle, icone, lien, id_general_info) VALUES
(DEFAULT, 'a_propos', NULL, NULL, NULL),
(DEFAULT, 'dgi', NULL, NULL, NULL),
(DEFAULT, 'mot_du_dgi', NULL, NULL, NULL),
(DEFAULT, '/legislation', NULL, NULL, NULL),
(DEFAULT, '/ressources', NULL, NULL, NULL),
(DEFAULT, '/analytiques_fiscales', NULL, NULL, NULL),
(DEFAULT, '/historique', NULL, NULL, NULL),
(DEFAULT, '/vision', NULL, NULL, NULL),
(DEFAULT, '/attributions', NULL, NULL, NULL),
(DEFAULT, '/e_service', NULL, NULL, NULL),
(DEFAULT, '/votre_avis', NULL, NULL, NULL),
(DEFAULT, 'centre_contact', NULL, NULL, NULL),
(DEFAULT, 'navigation', NULL, NULL, NULL),
(DEFAULT, 'nav_accueil', NULL, '#top', 13),
(DEFAULT, 'nav_a_propos', NULL, '#apropos', 13),
(DEFAULT, 'nav_documentations', NULL, '#documentations', 13),
(DEFAULT, 'nav_e_service', NULL, '#safi', 13),
(DEFAULT, 'nav_actualites', NULL, '#actualites', 13),
(DEFAULT, 'nav_espace', NULL, '#torohy', 13),
(DEFAULT, 'nav_contact', NULL, '#contact', 13),
(DEFAULT, 'actualites', NULL, NULL, NULL),
(DEFAULT, 'partenaire', NULL, NULL, NULL),
(DEFAULT, 'bureau', NULL, NULL, NULL),
(DEFAULT, 'contribuable', NULL, NULL, NULL),
(DEFAULT, 'recette', NULL, NULL, NULL),
(DEFAULT, 'appeler', NULL, '#appeler', NULL),
(DEFAULT, 'ecrire', NULL, '#ecrire', NULL),
(DEFAULT, 'visiter', NULL, '#visiter', NULL),
(DEFAULT, '/vision/valeurs et engagements', NULL, '/admin/explorer?path=/vision/valeurs et engagements', 8),
(DEFAULT, '/vision/projets de modernisation', NULL, '/admin/explorer?path=/vision/projets de modernisation', 8),
(DEFAULT, '/legislation/Recueil des textes', NULL, 'https://portal.impots.mg/textes/', 4),
(DEFAULT, '/legislation/Rescrit fiscal', NULL, 'https://portal.impots.mg/rescrit/', 4),
(DEFAULT, '/legislation/Brochures et guides', NULL, '/admin/explorer?path=/legislation/Brochures et guides', 4),
(DEFAULT, '/legislation/Calendrier Fiscal', NULL, '/admin/explorer?path=/legislation/Calendrier Fiscal', 4),
(DEFAULT, '/legislation/Conventions et Regimes Speciaux', NULL, '/admin/explorer?path=/legislation/Conventions et Regimes Speciaux', 4),
(DEFAULT, '/legislation/Codes et Manuels', NULL, '/admin/explorer?path=/legislation/Codes et Manuels', 4),
(DEFAULT, '/ressources/SIRH', NULL, 'https://sysinfo.mef.gov.mg:9101/ROHI/index.php/accueil/login', 5),
(DEFAULT, '/ressources/G-formation', NULL, 'https://portal.impots.mg/portal/utilisateur', 5),
(DEFAULT, '/ressources/Annuaire', NULL, '/admin/explorer?path=/ressources/Annuaire', 5),
(DEFAULT, '/ressources/Recrutements', NULL, '/admin/explorer?path=/ressources/Recrutements', 5),
(DEFAULT, '/ressources/Budget de la DGI', NULL, '/admin/explorer?path=/ressources/Budget de la DGI', 5),
(DEFAULT, '/ressources/RCTVA', NULL, '/admin/explorer?path=/ressources/RCTVA', 5),
(DEFAULT, '/e_service/Ehetra', NULL, 'https://e-hetra.impots.mg/', 10),
(DEFAULT, '/e_service/HetraOnline', NULL, 'https://hetraonline.impots.mg/', 10),
(DEFAULT, '/e_service/Valeur administrative des immeubles', NULL, 'https://immo.impots.mg/', 10),
(DEFAULT, '/e_service/Valeur administrative des vehicules', NULL, 'https://vehicule.impots.mg/', 10),
(DEFAULT, '/e_service/Attestation de destination', NULL, 'http://www.a2d.impots.mg/', 10),
(DEFAULT, '/e_service/Simulateur de calcul d''impot', NULL, 'https://www.impots.mg/fr/simulator', 10),
(DEFAULT, '/e_service/DConline', NULL, 'https://entreprises.impots.mg/dconline/', 10),
(DEFAULT, '/e_service/Annexe TVA', NULL, 'https://entreprises.impots.mg/nifonline/annexe_tva.php?bash=02122#accueil_menu_annexe_tva', 10);

-- Insertion dans la table langue
INSERT INTO public.langue (id, nom, icon) VALUES
(DEFAULT, 'MLG', NULL),
(DEFAULT, 'FRA', NULL),
(DEFAULT, 'ENG', NULL);

-- Insertion dans la table general_info_valeur
INSERT INTO public.general_info_valeur (id, titre, valeur, entete, bouton, id_langue, id_general_info) VALUES
(DEFAULT, 'Fandraisana', 'Fandraisana', '', '', 1, 14),
(DEFAULT, 'Momba ny', 'Momba ny', '', '', 1, 15),
(DEFAULT, 'Tahirin-kevitra', 'Tahirin-kevitra', '', '', 1, 16),
(DEFAULT, 'E-Service', 'E-Service', '', '', 1, 17),
(DEFAULT, 'Vaovao', 'Vaovao', '', '', 1, 18),
(DEFAULT, 'Espace citoyen', 'Espace citoyen', '', '', 1, 19),
(DEFAULT, 'Ivontoerana fifandraisana', 'Ivontoerana fifandraisana', '', '', 1, 20),
(DEFAULT, 'Vaovao', '', '', '', 1, 21),
(DEFAULT, 'Mpiara-miasa', '', '', '', 1, 22),
(DEFAULT, '<p>Bureaux operationnels</p>', '<p><br></p>', '153', '', 1, 23),
(DEFAULT, '<p>contribuables enregistres</p>', '<p><br></p>', '1585274', '', 1, 24),
(DEFAULT, '<p>recettes collectees</p>', '<p><br></p>', '4754124452922', '', 1, 25),
(DEFAULT, 'Accueil', 'Accueil', '', '', 2, 14),
(DEFAULT, 'A propos', 'A propos', '', '', 2, 15),
(DEFAULT, 'Documentations', 'Documentations', '', '', 2, 16),
(DEFAULT, 'E-Services', 'E-Services', '', '', 2, 17),
(DEFAULT, 'Actualites', 'Actualites', '', '', 2, 18),
(DEFAULT, 'Espace citoyen', 'Espace citoyen', '', '', 2, 19),
(DEFAULT, 'Centre de contact', 'Centre de contact', '', '', 2, 20),
(DEFAULT, 'actualites', '', '', '', 2, 21),
(DEFAULT, 'partenaires', '', '', '', 2, 22),
(DEFAULT, '<p>Bureaux operationnels</p>', '<p><br></p>', '153', '', 2, 23),
(DEFAULT, '<p>contribuables enregistres</p>', '<p><br></p>', '1585274', '', 2, 24),
(DEFAULT, '<p>recettes collectees</p>', '<p><br></p>', '4754124452922', '', 2, 25),
(DEFAULT, 'Home', 'Home', '', '', 3, 14),
(DEFAULT, 'About', 'About', '', '', 3, 15),
(DEFAULT, 'Documentations', 'Documentations', '', '', 3, 16),
(DEFAULT, 'E-Services', 'E-Services', '', '', 3, 17),
(DEFAULT, 'News', 'News', '', '', 3, 18),
(DEFAULT, 'Citizen Space', 'Citizen Space', '', '', 3, 19),
(DEFAULT, 'Contact Center', 'Contact Center', '', '', 3, 20),
(DEFAULT, 'news', '', '', '', 3, 21),
(DEFAULT, 'partners', '', '', '', 3, 22),
(DEFAULT, '<p>Bureaux operationnels</p>', '<p><br></p>', '153', '', 3, 23),
(DEFAULT, '<p>contribuables enregistres</p>', '<p><br></p>', '1585274', '', 3, 24),
(DEFAULT, '<p>recettes collectees</p>', '<p><br></p>', '4754124452922', '', 3, 25),
(DEFAULT, 'Mikasika', 'Mikasika', '', '', 1, 1),
(DEFAULT, 'A propos', 'A propos', '', '', 2, 1),
(DEFAULT, 'About', 'About', '', '', 3, 1),
(DEFAULT, 'Tantara', 'Tantara ny DGI', '', '', 1, 7),
(DEFAULT, 'Historique', 'Historique de la DGI', '', '', 2, 7),
(DEFAULT, 'History', 'History of the DGI', '', '', 3, 7),
(DEFAULT, '<p>Fahitana</p>', '<p>Telechargez ici l''ensemble des documents fondateurs </p><p>qui definissent notre engagement d''excellence </p><p>au service des contribuables et du developpement economique.</p>', '', '', 1, 8),
(DEFAULT, '<p>Vision</p>', '<p>Telechargez ici l''ensemble des documents fondateurs </p><p>qui definissent notre engagement d''excellence </p><p>au service des contribuables et du developpement economique.</p>', '', '', 2, 8),
(DEFAULT, '<p>Vision</p>', '<p>Telechargez ici l''ensemble des documents fondateurs </p><p>qui definissent notre engagement d''excellence </p><p>au service des contribuables et du developpement economique.</p>', '', '', 3, 8),
(DEFAULT, '<p>Adidy</p>', '<p>Adidy sy andraikitra</p>', '', '', 1, 9),
(DEFAULT, '<p>Attributions</p>', '<p>Explorer ici l''organisation </p><p>detaillee de la DGI </p><p>de Madagascar.</p><p><br></p>', '', '', 2, 9),
(DEFAULT, '<p>Responsibilities</p>', '<p>Duties and responsibilities</p>', '', '', 3, 9),
(DEFAULT, '<p>Votre Avis</p>', '<p>Exprimez votre avis sur nos services et contribuez a la lutte contre la fraude fiscale a travers notre plateforme securisee de signalement.</p>', 'espace citoyen', 'Donner mon avis', 2, 11),
(DEFAULT, '<p>Centre de Contact</p>', '<p>Bientot, notre centre d''appel sera disponible pour toute information sur vos demarches fiscales. Nos conseillers seront a votre ecoute, 24h/24 et 7j/7.</p>', 'Nous sommes la pour vous', 'Nous contacter', 2, 12),
(DEFAULT, '<p>Contact Center</p>', '<p>Bientot, notre centre d''appel sera disponible pour toute information sur vos demarches fiscales. Nos conseillers seront a votre ecoute, 24h/24 et 7j/7.</p>', 'We are here for you', 'Contact us', 3, 12),
(DEFAULT, '<p>Ivontoerana Fifandraisana</p>', '<p>Bientot, notre centre d''appel sera disponible pour toute information sur vos demarches fiscales. Nos conseillers seront a votre ecoute, 24h/24 et 7j/7.</p>', 'Miaraka aminay ianao', 'Mifandraisa aminay', 1, 12),
(DEFAULT, '<p>Loharano</p>', '<p>Accedez a toutes les informations sur l''organisation de la Direction Generale des Impots : son equipe dirigeante, ses responsables et ses structures operationnelles.</p>', '', 'hijery', 1, 5),
(DEFAULT, '<p>Ressources</p>', '<p>Accedez a toutes les informations sur l''organisation de la Direction Generale des Impots : son equipe dirigeante, ses responsables et ses structures operationnelles.</p>', '', 'voir plus', 2, 5),
(DEFAULT, '<p>Tenin''i DGI</p>', '<p>Engagee dans une transformation digitale majeure a travers son nouveau Systeme d''Administration Fiscale Integre (DEFAULTFI), la DGI vous accueille sur son portail en ligne, incarnant sa vision d''une administration fiscale innovante, transparente et pilier de l''emergence. Decouvrez nos services modernes, conçus pour garantir votre satisfaction et preserver un climat de confiance, conformement a l''image d''un gouvernement "manakaiky vahoaka".</p>', 'DGI', '', 1, 3),
(DEFAULT, '<p>Your Opinion</p>', '<p>Exprimez votre avis sur nos services et contribuez a la lutte contre la fraude fiscale a travers notre plateforme securisee de signalement.</p>', 'espace citoyen', 'Give feedback', 3, 11),
(DEFAULT, '<p>Hevitrao</p>', '<p>Exprimez votre avis sur nos services et contribuez a la lutte contre la fraude fiscale a travers notre plateforme securisee de signalement.</p>', 'espace citoyen', 'Omeo hevitra', 1, 11),
(DEFAULT, '<p>Mot du DGI</p>', '<p>Engagee dans une transformation digitale majeure a travers son nouveau Systeme d''Administration Fiscale Integre (DEFAULTFI), la DGI vous accueille sur son portail en ligne, incarnant sa vision d''une administration fiscale innovante, transparente et pilier de l''emergence. Decouvrez nos services modernes, conçus pour garantir votre satisfaction et preserver un climat de confiance, conformement a l''image d''un gouvernement "manakaiky vahoaka".</p>', 'DGI', '', 2, 3),
(DEFAULT, '<p>E-Service</p>', '<p>Simplifiez vos obligations fiscales avec SAFI, la plateforme digitale de la Direction Generale des Impots qui vous permet de declarer, payer et suivre vos impots en ligne, avec un systeme d''alertes personnalisees pour une gestion optimale de votre compte.</p>', 'Demarches fiscales', 'Se connecter', 2, 10),
(DEFAULT, '<p>Legislation</p>', '<p>Retrouvez ici l''ensemble des textes et reglementations en vigueur regissant la fiscalite malgache, regulierement actualises pour vous permettre de mieux comprendre vos droits et obligations fiscales.</p>', '', 'voir plus', 2, 4),
(DEFAULT, '<p>Legislation</p>', '<p>Retrouvez ici l''ensemble des textes et reglementations en vigueur regissant la fiscalite malgache, regulierement actualises pour vous permettre de mieux comprendre vos droits et obligations fiscales.</p>', '', 'show more', 3, 4),
(DEFAULT, '<p>Lalana</p>', '<p>Retrouvez ici l''ensemble des textes et reglementations en vigueur regissant la fiscalite malgache, regulierement actualises pour vous permettre de mieux comprendre vos droits et obligations fiscales.</p>', '', 'hijery', 1, 4),
(DEFAULT, '<p>Resources</p>', '<p>Accedez a toutes les informations sur l''organisation de la Direction Generale des Impots : son equipe dirigeante, ses responsables et ses structures operationnelles.</p>', '', 'show more', 3, 5),
(DEFAULT, '<p>Famakafakana ara-bola</p>', '<p>Consultez dans cette rubrique les documents d''analyse approfondis retraçant ses performances en matiere de mobilisation des recettes fiscales, statistiques periodiques des realisations, etudes sectorielles, publications economiques, rapports detailles d''activites, etc.</p>', '', 'hijery', 1, 6),
(DEFAULT, '<p>E-Service</p>', '<p>Simplifiez vos obligations fiscales avec SAFI, la plateforme digitale de la Direction Generale des Impots qui vous permet de declarer, payer et suivre vos impots en ligne, avec un systeme d''alertes personnalisees pour une gestion optimale de votre compte.</p>', 'Demarches fiscales', 'Se connecter', 3, 10),
(DEFAULT, '<p>E-Service</p>', '<p>Simplifiez vos obligations fiscales avec SAFI, la plateforme digitale de la Direction Generale des Impots qui vous permet de declarer, payer et suivre vos impots en ligne, avec un systeme d''alertes personnalisees pour une gestion optimale de votre compte.</p>', 'Demarches fiscales', 'Se connecter', 1, 10),
(DEFAULT, '<p>Tale jeneralin''ny hetra</p>', '<p>Germain</p>', 'Ny mombamomba', '', 1, 2),
(DEFAULT, '<p>Directeur General des Impots</p>', '<p>Germain</p>', 'a propos', '', 2, 2),
(DEFAULT, '<p>Director General of Taxes</p>', '<p>Germain</p>', 'about', '', 3, 2),
(DEFAULT, '<p>Analytiques fiscales</p>', '<p>Consultez dans cette rubrique les documents d''analyse approfondis retraçant ses performances en matiere de mobilisation des recettes fiscales, statistiques periodiques des realisations, etudes sectorielles, publications economiques, rapports detailles d''activites, etc.</p>', '', 'voir plus', 2, 6),
(DEFAULT, '<p>Fiscal analytics</p>', '<p>Consultez dans cette rubrique les documents d''analyse approfondis retraçant ses performances en matiere de mobilisation des recettes fiscales, statistiques periodiques des realisations, etudes sectorielles, publications economiques, rapports detailles d''activites, etc.</p>', '', 'show more', 3, 6),
(DEFAULT, '<p>Word of the DGI</p>', '<p>Engagee dans une transformation digitale majeure a travers son nouveau Systeme d''Administration Fiscale Integre (DEFAULTFI), la DGI vous accueille sur son portail en ligne, incarnant sa vision d''une administration fiscale innovante, transparente et pilier de l''emergence. Decouvrez nos services modernes, conçus pour garantir votre satisfaction et preserver un climat de confiance, conformement a l''image d''un gouvernement "manakaiky vahoaka".</p>', 'DGI', '', 3, 3),
(DEFAULT, 'Appeler', 'Secretariat DGI : +261 20 85 287 08<br>Cellule Communication DGI : +261 32 12 015 03<br>Cellule eHetra : +261 32 12 015 04<br>Hotline SSIF : +261 32 12 011 74 / +261 34 49 431 52', 'NOUS CONTACTER', '', 2, 26),
(DEFAULT, 'Ecrire', 'Secretariat DGI : dgimpots@moov.mg<br>Cellule Communication DGI : communication.dgimpots@gmail.com<br>Hotline SSIF : impot.ssif.hotline@gmail.com', '', '', 2, 27),
(DEFAULT, 'Visiter', 'Immeuble de l''Economie et des Finances<br>4eme etage - porte 420<br>Antaninarenina Antananarivo', '', '', 2, 28),
(DEFAULT, 'Call', 'DGI Secretariat: +261 20 85 287 08<br>DGI Communication Unit: +261 32 12 015 03<br>eHetra Unit: +261 32 12 015 04<br>SSIF Hotline: +261 32 12 011 74 / +261 34 49 431 52', 'CONTACT US', '', 3, 26),
(DEFAULT, 'Write', 'DGI Secretariat: dgimpots@moov.mg<br>DGI Communication Unit: communication.dgimpots@gmail.com<br>SSIF Hotline: impot.ssif.hotline@gmail.com', '', '', 3, 27),
(DEFAULT, 'Visit', 'Ministry of Economy and Finance Building<br>4th floor - door 420<br>Antaninarenina Antananarivo', '', '', 3, 28),
(DEFAULT, 'Antsoy', 'Sekreterian''ny DGI : +261 20 85 287 08<br>Sampan''asa Fampandraharahana DGI : +261 32 12 015 03<br>Sampan''asa eHetra : +261 32 12 015 04<br>Hotline SSIF : +261 32 12 011 74 / +261 34 49 431 52', 'Hifandray aminay', '', 1, 26),
(DEFAULT, 'Hanoratra', 'Sekreterian''ny DGI : dgimpots@moov.mg<br>Sampan''asa Fampandraharahana DGI : communication.dgimpots@gmail.com<br>Hotline SSIF : impot.ssif.hotline@gmail.com', '', '', 1, 27),
(DEFAULT, 'Hitsidika', 'Tranon''ny Toekarena sy ny Finansa<br>4eme etage - varavarana 420<br>Antaninarenina Antananarivo', '', '', 1, 28),
(DEFAULT, '', '', '', '', 1, 29),
(DEFAULT, '', '', '', '', 2, 29),
(DEFAULT, '', '', '', '', 3, 29),
(DEFAULT, '', '', '', '', 1, 30),
(DEFAULT, '', '', '', '', 2, 30),
(DEFAULT, '', '', '', '', 3, 30),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 31),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 31),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 31),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 32),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 32),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 32),
(DEFAULT, '<p><br></p>', '<p>Retrouvez tous nos guides et brochures d''information pour vous accompagner dans la comprehension et l''accomplissement de vos obligations fiscales.</p>', '', '', 1, 33),
(DEFAULT, '<p><br></p>', '<p>Retrouvez tous nos guides et brochures d''information pour vous accompagner dans la comprehension et l''accomplissement de vos obligations fiscales.</p>', '', '', 2, 33),
(DEFAULT, '<p><br></p>', '<p>Retrouvez tous nos guides et brochures d''information pour vous accompagner dans la comprehension et l''accomplissement de vos obligations fiscales.</p>', '', '', 3, 33),
(DEFAULT, '', '', '', '', 1, 34),
(DEFAULT, '', '', '', '', 2, 34),
(DEFAULT, '', '', '', '', 3, 34),
(DEFAULT, '', '', '', '', 1, 35),
(DEFAULT, '', '', '', '', 2, 35),
(DEFAULT, '', '', '', '', 3, 35),
(DEFAULT, '<p><br></p>', '<p>Consultez ici l''ensemble des codes fiscaux et manuels de reference.</p>', '', '', 1, 36),
(DEFAULT, '<p><br></p>', '<p>Consultez ici l''ensemble des codes fiscaux et manuels de reference.</p>', '', '', 2, 36),
(DEFAULT, '<p><br></p>', '<p>Consultez ici l''ensemble des codes fiscaux et manuels de reference.</p>', '', '', 3, 36),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 37),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 37),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 37),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 38),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 38),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 38),
(DEFAULT, '<p><br></p>', '<p>Accedez aux coordonnees completes de nos services centraux et regionaux pour faciliter vos contacts et demarches aupres de la DGI.</p>', '', '', 1, 39),
(DEFAULT, '<p><br></p>', '<p>Accedez aux coordonnees completes de nos services centraux et regionaux pour faciliter vos contacts et demarches aupres de la DGI.</p>', '', '', 2, 39),
(DEFAULT, '<p><br></p>', '<p>Accedez aux coordonnees completes de nos services centraux et regionaux pour faciliter vos contacts et demarches aupres de la DGI.</p>', '', '', 3, 39),
(DEFAULT, '', '', '', '', 1, 40),
(DEFAULT, '', '', '', '', 2, 40),
(DEFAULT, '', '', '', '', 3, 40),
(DEFAULT, '', '', '', '', 1, 41),
(DEFAULT, '', '', '', '', 2, 41),
(DEFAULT, '', '', '', '', 3, 41),
(DEFAULT, '', '', '', '', 1, 42),
(DEFAULT, '', '', '', '', 2, 42),
(DEFAULT, '', '', '', '', 3, 42),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 1, 43),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 2, 43),
(DEFAULT, '<p><br></p>', '<p><br></p>', '', '', 3, 43),
(DEFAULT, '', '', '', '', 1, 44),
(DEFAULT, '', '', '', '', 2, 44),
(DEFAULT, '', '', '', '', 3, 44),
(DEFAULT, '', '', '', '', 1, 45),
(DEFAULT, '', '', '', '', 2, 45),
(DEFAULT, '', '', '', '', 3, 45),
(DEFAULT, '', '', '', '', 1, 46),
(DEFAULT, '', '', '', '', 2, 46),
(DEFAULT, '', '', '', '', 3, 46),
(DEFAULT, '', '', '', '', 1, 47),
(DEFAULT, '', '', '', '', 2, 47),
(DEFAULT, '', '', '', '', 3, 47),
(DEFAULT, '', '', '', '', 1, 48),
(DEFAULT, '', '', '', '', 2, 48),
(DEFAULT, '', '', '', '', 3, 48),
(DEFAULT, '', '', '', '', 1, 49),
(DEFAULT, '', '', '', '', 2, 49),
(DEFAULT, '', '', '', '', 3, 49),
(DEFAULT, '', '', '', '', 1, 50),
(DEFAULT, '', '', '', '', 2, 50),
(DEFAULT, '', '', '', '', 3, 50);